/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hamburgueria;

/**
 *
 * @author PC Casa
 */
public class RegistroDeVendas extends javax.swing.JFrame {

    /**
     * Creates new form RegistroDeVendas
     */
    public RegistroDeVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelRegistroDeVendas = new javax.swing.JLabel();
        caixaPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 900));
        setMinimumSize(new java.awt.Dimension(900, 900));
        setPreferredSize(new java.awt.Dimension(900, 900));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRegistroDeVendas.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        labelRegistroDeVendas.setForeground(new java.awt.Color(255, 153, 0));
        labelRegistroDeVendas.setText("Registro de Vendas");
        jPanel1.add(labelRegistroDeVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        caixaPesquisa.setText("Pesquisar:");
        caixaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(caixaPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 90, 480, 30));

        tabelaVendas.setBackground(new java.awt.Color(0, 0, 0));
        tabelaVendas.setForeground(new java.awt.Color(255, 255, 255));
        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cheddar", "25", "23,99", "599,75"},
                {"2", "Fraldinha", "18", "22,99", "413,82"},
                {"3", "Tuba", "19", "25,99", "493,81"}
            },
            new String [] {
                "ID", "Hamburguer", "Qtd", "Valor Unitário", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tabelaVendas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 590, 210));

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 90, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void caixaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaPesquisaActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        TelaVendas novaTelaVendas = new TelaVendas();
        novaTelaVendas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDeVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField caixaPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelRegistroDeVendas;
    private javax.swing.JTable tabelaVendas;
    // End of variables declaration//GEN-END:variables
}
